CustomGridViewAndTagCloud/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CustomGridViewAndTagCloud.Models;

namespace CustomGridViewAndTagCloud.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var model = new DataContext().GetAllArtists();
            return View("Index", model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CustomGridViewAndTagCloud/ViewComponents/TagCloudViewComponent.cs
using CustomGridViewAndTagCloud.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CustomGridViewAndTagCloud.ViewComponents
{
    public class TagCloudViewComponent : ViewComponent
    {
        private readonly DataContext _context;
        public TagCloudViewComponent()
        {
            _context = new DataContext(); ;
        }

        public IViewComponentResult Invoke()
        {
            var items = (from songs in _context.GetSong()
                         join genres in _context.GetAllGenre() on songs.GenreId equals
                         genres.GenreLookUpId
                         where songs.GenreId.HasValue
                         select new { genres.GenreName, songs.GenreId }).ToList();

            var grouped = items.GroupBy(s => s.GenreName).Select(
            gen => new { Name = gen.Key, Count = gen.Count() });


            var model = new TagCloud();


            foreach (var item in grouped)
            {
                var cti = new TagCloudItem
                {
                    DisplayText = item.Name,
                    Url = string.Concat("/Genres/", item.Name),
                    Weight = item.Count
                };

                model.AddItem(cti);
            }
            return View(model);
        }
    }
}

CustomGridViewAndTagCloud/Views/Home/Index.cshtml
@model IList<Artist>

@{
    ViewData["Title"] = "Home Page";
}
<h1>Tag helper and view component inside a container</h1>
This is an example of a Tag Cloud created using a ViewComponent and you'll see the most music genre people are voting in this web site
<h2>Tag Cloud with view component</h2>
<div class="row">
    <div class="col-lg-5">
        @await Component.InvokeAsync("TagCloud");
    </div>
</div>
<br />
<br />

<h2>DataList with tag helper</h2>
<column-list asp-number-of-columns="3"
             asp-for="@Model"
             asp-view-component="ArtistCard"></column-list>